### ISSUE TITLE
Add spatie role-based permission

### ISSUE THREAD

**Issue by metallurgical** [metallurgical/open-invoice-generator#3]
Add spatie role-based permission

**Comment by metallurgical** [comment]
Please use this package https://spatie.be/docs/laravel-permission/v5/introduction

**Comment by cdterry87** [comment]
@metallurgical I did the initial setup for the spatie permissions package in PR #16 . 

I also went one step further and setup an initial seeder for the roles and added two role types: `user` and `admin`. I wasn't sure what specific roles and permissions you'd need, so I just setup these two roles initially and added them to the database seeder so it will set them up automatically when the database is initially seeded.
